# Generated by Django 3.1 on 2020-09-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200912_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='price',
            field=models.FloatField(default=8.0),
            preserve_default=False,
        ),
    ]
